config/routes.rb
Rails.application.routes.draw do
  resources :reviews
  get 'reviews/new/:claim_id', to: 'reviews#new', as: 'review_new'
  get 'participations/join/:claim_id', to: 'participations#join', as: 'participation_join'

  get 'participations/', to: 'participations#index'
  delete 'participations/:id', to: 'participations#destroy', as: 'participation'

  resources :claims
  get 'claims/:id/sendmail', to: 'claims#send_email', as: 'claim_send_email'
  mount Upmin::Engine => '/admin'
  root to: 'visitors#index'
  devise_for :users
  resources :users
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
  def index
    @claims = Claim.all
  end
end

app/views/visitors/index.html.slim
- model_class = Claim
.page-header
  h1=t '.title', :default => model_class.model_name.human.pluralize.titleize
table.table.table-striped
  thead
    tr
      th= model_class.human_attribute_name(:id)
      th= model_class.human_attribute_name(:title)
      th= model_class.human_attribute_name(:description)
      th= 'Author'
      th= model_class.human_attribute_name(:created_at)
      th
  tbody
    - @claims.each do |claim|
        - if claim.published?
          tr
            td= claim.id
            td= claim.title
            td= claim.description
            td= Participation.where(claim_id: claim.id).where(author: true).first.user.email
            td=l claim.created_at, format: :long
            td
                = link_to claim_path(claim), :class => 'btn btn-xs', :title => "#{ t('.show', :default => t('helpers.links.show')) }" do
                    span
                        = 'Show'
                - if !current_user.nil? && Participation.where(claim_id: claim.id).where(user_id: current_user.id).count == 0

                     = link_to participation_join_path(claim), :class => 'btn btn-xs', :title =>"Join the claim" do
                      span
                          = 'Contribute'