config/routes.rb
Rails.application.routes.draw do
  resources :reviews
  get 'reviews/new/:claim_id', to: 'reviews#new', as: 'review_new'
  get 'participations/join/:claim_id', to: 'participations#join', as: 'participation_join'

  get 'participations/', to: 'participations#index'
  delete 'participations/:id', to: 'participations#destroy', as: 'participation'

  resources :claims
  get 'claims/:id/sendmail', to: 'claims#send_email', as: 'claim_send_email'
  mount Upmin::Engine => '/admin'
  root to: 'visitors#index'
  devise_for :users
  resources :users
end

app/models/claim.rb
class Claim < ActiveRecord::Base
    has_many :participations
    has_many :evidences
    has_many :reviews
    mount_uploader :picture, ClaimUploader
    enum state: [:draft, :published]
end

app/controllers/claims_controller.rb
class ClaimsController < ApplicationController
  before_action :authenticate_user!, only: [:index, :new, :edit, :create, :destroy, :update]
  before_action :set_claim, only: [:show, :edit, :update, :destroy, :send_email]

  # GET /claims
  # GET /claims.json
  def index
    if current_user.admin?
        @claims = Claim.all
    else
        @participations = Participation.where(user_id: current_user.id).where(author: true)
        @claims = []
        @participations.each do |p|
            @claims << p.claim
        end
    end
  end

  # GET /claims/1
  # GET /claims/1.json
  def show
  end

  # GET /claims/new
  def new
    @claim = Claim.new
  end

  # GET /claims/1/edit
  def edit
      if current_user != Participation.where(claim_id: @claim.id).where(author: true).first.user
          redirect_to claims_url
      end
  end

  # POST /claims
  # POST /claims.json
  def create
    @claim = Claim.new(claim_params)
    @claim.mailSend = false

    @participation = Participation.new
    @participation.user = current_user
    @participation.claim = @claim
    @participation.author = true
    respond_to do |format|
      if @claim.save && @participation.save
        if !params[:evidences].nil?
          params[:evidences].each do |picture|
            @claim.evidences.create(picture: picture, claim_id: @claim.id)
          end
        end
        format.html { redirect_to @claim, notice: 'Claim was successfully created.' }
        format.json { render :show, status: :created, location: @claim }
      else
        format.html { render :new }
        format.json { render json: @claim.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /claims/1
  # PATCH/PUT /claims/1.json
  def update
    if current_user == Participation.where(claim_id: @claim.id).where(author: true).first.user
      respond_to do |format|
        if @claim.update(claim_params)
          format.html { redirect_to @claim, notice: 'Claim was successfully updated.' }
          format.json { render :show, status: :ok, location: @claim }
        else
          format.html { render :edit }
          format.json { render json: @claim.errors, status: :unprocessable_entity }
        end
      end
    else
      redirect_to claims_url
    end
  end

  # DELETE /claims/1
  # DELETE /claims/1.json
  def destroy
    if current_user.admin? || @claim.user = current_user
      @claim.evidences.each do |evidence|
        evidence.destroy
      end
      @claim.destroy
      respond_to do |format|
        format.html { redirect_to claims_url, notice: 'Claim was successfully destroyed.' }
        format.json { head :no_content }
      end
    else
      redirect_to claims_url
    end
  end

  def send_email
    if current_user.admin? && !@claim.mailSend
      require 'application_mailer'
      ApplicationMailer.send_mail_claim(@claim)

      @claim.mailSend = true
      @claim.save

      respond_to do |format|
        format.html { redirect_to claims_url, notice: 'Mail was successfully changed.' }
        format.json { head :no_content }
      end
    else
      redirect_to claims_url
    end
  end

  def send_multiple_emails
    Claim.all.each do |claim|
      if !claim.mailSend && claim.created_at < Date.now-30.seconds
        send_mail_claim(claim)
        claim.mailSend = true
        claim.save
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_claim
      @claim = Claim.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def claim_params
      params.require(:claim).permit(:title, :description, :state, :picture)
    end
end

app/helpers/claims_helper.rb
module ClaimsHelper
end

app/views/claims/_form.html.slim
= form_for @claim, :html => { :class => "form-horizontal" } do |f|
  .form-group
    = f.label :title, :class => 'control-label col-md-2'
    .col-md-10
      = f.text_field :title, :class => 'text_field form-control'
  .form-group
    = f.label :description, :class => 'control-label col-md-2'
    .col-md-10
      = f.text_field :description, :class => 'text_field form-control'
  .form-group
    = f.label :state, :class => 'control-label col-md-2'
    .col-md-10
    = f.select :state, Claim.states.keys.to_a.map { |w| [w.humanize, w] }
  .form-group
    = f.label :picture, :class => 'control-label col-md-2'
    .col-md-10
      = f.file_field :picture, :class => 'file_field form-control'
  .form-group
    = f.label :evidences, :class => 'control-label col-md-2'
    .col-md-10
      = file_field_tag "evidences[]", multiple: true, :class => 'file_field form-control'
  .form-group
    .col-md-offset-2.col-md-10
      = f.submit nil, :class => 'btn btn-primary'
      = link_to t('.cancel', :default => t("helpers.links.cancel")), claims_path, :class => 'btn btn-default'

app/views/claims/edit.html.slim
- model_class = Claim
div class="page-header"
  h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/claims/index.html.slim
- model_class = Claim
.page-header
  h1= 'Your claims'
table.table.table-striped
  thead
    tr
      th= model_class.human_attribute_name(:id)
      th= model_class.human_attribute_name(:title)
      th= model_class.human_attribute_name(:description)
      th= 'Author'
      th= model_class.human_attribute_name(:created_at)
      th= 'State'
      th
      th=t '.actions', :default => t("helpers.actions")
  tbody
    - @claims.each do |claim|
      tr
        td= claim.id
        td= claim.title
        td= claim.description
        td= Participation.where(claim_id: claim.id).where(author: true).first.user.email
        td=l claim.created_at, format: :long
        td= claim.state.humanize
        td= claim.mailSend
        td
            = link_to claim_path(claim), :class => 'btn btn-xs', :title => "#{ t('.show', :default => t('helpers.links.show')) }" do
              = glyph 'info-sign'
            - if current_user == Participation.where(claim_id: claim.id).where(author: true).first.user
                = link_to edit_claim_path(claim), :class => 'btn btn-xs', :title => "#{ t('.edit', :default => t('helpers.links.edit')) }" do
                  = glyph 'pencil'
            - if current_user.admin?
                = link_to review_new_path(claim), :class => 'btn btn-xs', :title => "Create a review for this claim" do
                  = glyph 'tag'
                = link_to claim_send_email_path(claim), :class => 'btn btn-xs', :title => "Send an email to the participant" do
                  = glyph 'send'

            = link_to claim_path(claim), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs', :title => "#{ t('.destroy', :default => t('helpers.links.destroy')) }"  do
              = glyph 'remove'

= link_to t('.new', :default => t("helpers.links.new")), new_claim_path, :class => 'btn btn-primary'

app/views/claims/new.html.slim
- model_class = Claim
.page-header
  h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/claims/show.html.slim
- model_class = Claim
div class="page-header"
  h1=t '.title', :default => model_class.model_name.human.titleize

-if !@claim.reviews.blank?
  h2= 'Reviews for your claim'
  table.table.table-striped
    thead
      tr
        th= model_class.human_attribute_name(:id)
        th= model_class.human_attribute_name(:content)
        th= model_class.human_attribute_name(:kind)
        th= model_class.human_attribute_name(:claim_id)
        th= model_class.human_attribute_name(:created_at)
        th=t '.actions', :default => t("helpers.actions")
    tbody
      - @claim.reviews.each do |review|
        tr
          td= review.id
          td= review.content
          td= review.kind
          td
            = link_to claim_path(review.claim), :title => "See the claim" do
              = review.claim.title
          td=l review.created_at, format: :long
          td
            = link_to review_path(review), :class => 'btn btn-xs', :title => "#{ t('.show', :default => t('helpers.links.show')) }" do
              = glyph 'info-sign'

            - if current_user.admin?
              = link_to edit_review_path(review), :class => 'btn btn-xs', :title => "#{ t('.edit', :default => t('helpers.links.edit')) }" do
                = glyph 'pencil'
              = link_to review_path(review), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs', :title => "#{ t('.destroy', :default => t('helpers.links.destroy')) }"  do
                = glyph 'remove'

.fieldset
  dl
      dt.label.label-default= model_class.human_attribute_name(:title)
      dd
        pre.prettyprint= @claim.title
      dt.label.label-default = model_class.human_attribute_name(:description)
      dd
        pre.prettyprint= @claim.description
      dt.label.label-default = 'Author'
      dd
        pre.prettyprint= Participation.where(claim_id: @claim.id).where(author: true).first.user.email
      dt.label.label-default = model_class.human_attribute_name(:picture)
      dd
        img src = @claim.picture.url
      dt.label.label-default = model_class.human_attribute_name(:evidences)
      - for evidence in @claim.evidences
        img src = evidence.picture.url

.form-group
  - if current_user.nil?
    = link_to t('.back', :default => t("helpers.links.back")),  root_path , :class => 'btn btn-default'

  - else
    = link_to t('.back', :default => t("helpers.links.back")), claims_path, :class => 'btn btn-default'
    - if current_user == Participation.where(claim_id: @claim.id).where(author: true).first.user
        '
        = link_to t('.edit', :default => t("helpers.links.edit")), edit_claim_path(@claim), :class => 'btn btn-default'
    - if current_user.admin? || current_user == Participation.where(claim_id: @claim.id).where(author: true).first.user
        '
        = link_to t('.destroy', :default => t("helpers.links.destroy")), claim_path(@claim), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'