config/routes.rb
Rails.application.routes.draw do
  resources :reviews
  get 'reviews/new/:claim_id', to: 'reviews#new', as: 'review_new'
  get 'participations/join/:claim_id', to: 'participations#join', as: 'participation_join'

  get 'participations/', to: 'participations#index'
  delete 'participations/:id', to: 'participations#destroy', as: 'participation'

  resources :claims
  get 'claims/:id/sendmail', to: 'claims#send_email', as: 'claim_send_email'
  mount Upmin::Engine => '/admin'
  root to: 'visitors#index'
  devise_for :users
  resources :users
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :authenticate_user!, only: [:index, :new, :edit, :create, :destroy, :update]
  before_action :is_admin, except: [:index, :show]
  before_action :set_review, only: [:show, :edit, :update, :destroy]

  # GET /reviews
  # GET /reviews.json
  def index
    if current_user.admin?
      @reviews = Review.all
    else
      @participations = Participation.where(user_id: current_user.id).where(author: true)
      @reviews = []
      @participations.each do |p|
        p.claim.reviews.each do |review|
          @reviews << review
        end
      end
    end
  end

  # GET /reviews/1
  # GET /reviews/1.json
  def show
  end

  # GET /reviews/new
  def new
    @review = Review.new
    @review.claim_id = params[:claim_id]
  end

  # GET /reviews/1/edit
  def edit
  end

  # POST /reviews
  # POST /reviews.json
  def create
    @review = Review.new(review_params)
    @review.claim_id = params[:review][:claim_id]
    if @review.reject? && !@review.claim.nil?
      @review.claim.state = :draft
      @review.claim.save
    end
    respond_to do |format|
      if @review.save
        format.html { redirect_to @review, notice: 'Review was successfully created.' }
        format.json { render :show, status: :created, location: @review }
      else
        format.html { render :new }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reviews/1
  # PATCH/PUT /reviews/1.json
  def update
    respond_to do |format|
      if @review.update(review_params)
        format.html { redirect_to @review, notice: 'Review was successfully updated.' }
        format.json { render :show, status: :ok, location: @review }
      else
        format.html { render :edit }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reviews/1
  # DELETE /reviews/1.json
  def destroy
    @review.destroy
    respond_to do |format|
      format.html { redirect_to reviews_url, notice: 'Review was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def is_admin
      if !current_user.admin?
        respond_to do |format|
          format.html { redirect_to reviews_url, notice: 'You wot m8.' }
          format.json { head :no_content }
        end
      end
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_review
      @review = Review.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def review_params
      params.require(:review).permit(:content, :kind)
    end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/reviews/_form.html.slim
= form_for @review, :html => { :class => "form-horizontal" } do |f|
  .form-group
    = f.label :content, :class => 'control-label col-md-2'
    .col-md-10
      = f.text_field :content, :class => 'text_field form-control'
  .form-group
    = f.label :kind, :class => 'control-label col-md-2'
    .col-md-10
      = f.select :kind, Review.kinds.keys.to_a.map { |w| [w.humanize, w] }
  .form-group
    .col-md-offset-2.col-md-10
      = f.hidden_field :claim_id
      = f.submit nil, :class => 'btn btn-primary'
      = link_to t('.cancel', :default => t("helpers.links.cancel")), reviews_path, :class => 'btn btn-default'

app/views/reviews/edit.html.slim
- model_class = Review
div class="page-header"
  h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/reviews/index.html.slim
- model_class = Review
.page-header
  h1=t '.title', :default => model_class.model_name.human.pluralize.titleize
table.table.table-striped
  thead
    tr
      th= model_class.human_attribute_name(:id)
      th= model_class.human_attribute_name(:content)
      th= model_class.human_attribute_name(:kind)
      th= model_class.human_attribute_name(:claim_id)
      th= model_class.human_attribute_name(:created_at)
      th=t '.actions', :default => t("helpers.actions")
  tbody
    - @reviews.each do |review|
      tr
        td= review.id
        td= review.content
        td= review.kind
        td
          = link_to claim_path(review.claim), :title => "See the claim" do
            = review.claim.title
        td=l review.created_at, format: :long
        td
          = link_to review_path(review), :class => 'btn btn-xs', :title => "#{ t('.show', :default => t('helpers.links.show')) }" do
            = glyph 'info-sign'

          - if current_user.admin?
            = link_to edit_review_path(review), :class => 'btn btn-xs', :title => "#{ t('.edit', :default => t('helpers.links.edit')) }" do
              = glyph 'pencil'
            = link_to review_path(review), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs', :title => "#{ t('.destroy', :default => t('helpers.links.destroy')) }"  do
              = glyph 'remove'

= link_to t('.new', :default => t("helpers.links.new")), new_review_path, :class => 'btn btn-primary'

app/views/reviews/new.html.slim
- model_class = Review
.page-header
  h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/reviews/show.html.slim
- model_class = Review
div class="page-header"
  h1=t '.title', :default => model_class.model_name.human.titleize

.fieldset
  dl
      dt.label.label-default= model_class.human_attribute_name(:content)
      dd
        pre.prettyprint= @review.content
      dt.label.label-default= model_class.human_attribute_name(:kind)
      dd
        pre.prettyprint= @review.kind.humanize
      dt.label.label-default= model_class.human_attribute_name(:claim_id)
      dd
        pre.prettyprint= @review.claim_id
      dt.label.label-default= "Claim author"
      dd
        pre.prettyprint= @review.claim.participations.select{ |p| p.author}.first.user.email

.form-group
  = link_to t('.back', :default => t("helpers.links.back")), reviews_path, :class => 'btn btn-default'
  '
  = link_to t('.edit', :default => t("helpers.links.edit")), edit_review_path(@review), :class => 'btn btn-default'
  '
  = link_to t('.destroy', :default => t("helpers.links.destroy")), review_path(@review), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'